"""add unique constraint to bookmarks

Revision ID: 6bd30232081b
Revises: f7996e078f30
Create Date: 2026-10-06 16:30:42.996948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd30232081b'
down_revision: Union[str, Sequence[str], None] = 'f7996e078f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_post_bookmark', 'bookmarks', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_post_bookmark', 'bookmarks', type_='unique')
    # ### end Alembic commands ###
